X = 20
PPQ = 480
DEFAULT_MIDI_NOTE = 60
DEFAULT_RHYTHM_VALUE = 4
DEFAULT_VELOCITY_VALUE = 63
DEFAULT_PITCH_CLASS_SYMBOLS_TO_MIDI_NOTES = {
    "0": DEFAULT_MIDI_NOTE,
    "1": DEFAULT_MIDI_NOTE + 1,
    "2": DEFAULT_MIDI_NOTE + 2,
    "3": DEFAULT_MIDI_NOTE + 3,
    "4": DEFAULT_MIDI_NOTE + 4,
    "5": DEFAULT_MIDI_NOTE + 5,
    "6": DEFAULT_MIDI_NOTE + 6,
    "7": DEFAULT_MIDI_NOTE + 7,
    "8": DEFAULT_MIDI_NOTE + 8,
    "9": DEFAULT_MIDI_NOTE + 9,
    "A": DEFAULT_MIDI_NOTE + 10,
    "B": DEFAULT_MIDI_NOTE + 11,
    "a": DEFAULT_MIDI_NOTE + 10,
    "b": DEFAULT_MIDI_NOTE + 11,
}
